### ISSUE TITLE
bug : cannot run sims anymore

### ISSUE THREAD

**Issue by julienguy** [desihub/specsim#34] opened 2016-02-23 11:18 UTC
I am trying to do a simple sky simulation and get a bug with 
```
import specsim.config
import specsim.simulator
config = specsim.config.load_config('desi')
config.update()
qsim = specsim.simulator.Simulator(config)
```

and get an error message ending with 
```
File "/usr/local/lib/python2.7/dist-packages/astropy/utils/data.py", line 202, in get_readable_fileobj
    fileobj = open(name_or_obj, 'rb')
IOError: [Errno 2] No such file or directory: '/home/guy/software/DESI/desimodel_svn/0.4//data/throughput/thru-R.fits'
```
we don't have thru-R.fits but thru-r.fits.

I cannot track this further because the whole code has changed.

I am also worried to find a file specsim/specsim/data/config/desi.yaml
which contains duplicated info with desimodel/data/desi.yaml

**Comment by dkirkby** [comment] 2016-02-23 15:02
Thanks for catching this.  The reason I didn't notice this earlier is [embarrassing](http://www.cio.com/article/2868393/linus-torvalds-apples-hfs-is-probably-the-worst-file-system-ever.html).

I have pushed the fix to the master branch, but it is simple enough that you don't need to update. Instead, you can just fix the filenames in the 3 lines of `desi.yaml` that specify these filenames, e.g.
```
path: throughput/thru-r.fits
```

The duplicated YAML constants were an unavoidable (and perhaps temporary) side effect of a significant re-organization of the code that enables simulations of other instruments (e.g., eBOSS to calibrate DESI simulations) and running regression tests independent of files in desimodel.

There are only 14 duplicated constants, which are documented here:

  http://specsim.readthedocs.org/en/stable/config.html#desi-configuration

One benefit of the duplication is that these constants now have machine-readable units attached.  Feel free to open a new issue if you have ideas for how to improve this situation.

**Closed by dkirkby** 2016-02-23 15:02 UTC
Labels: bug
